
import PlatformBase from '../PlatformBase.js';
import { JOYSTICK_TOUCH_MODE } from '../../Constants.js';

const DOS = {
    ...PlatformBase,
    platform_id: 'dos',
    core: 'dosbox_pure',
    uses_pthreads: true,
    platform_name: 'DOS PC (Pentium + SB + SVGA)',
    short_name: 'DOS',
    theme: {
        '--color0': '#0000AA',
        '--color1': '#FFFF55',
        '--color2': '#FFFFFF',
        '--color3': '#AA0101',
        '--color4': '#FFFF55',
        '--font': 'VGA',
        '--fontsize': '1.1em',
        '--cursorwidth': '0.5em',
        '--portrait-fontsize': '100%'
    },
    guessConfig: (fileName) => {
        return {
            dosbox_pure_memory_size: "16",
            dosbox_pure_voodoo: "off",
            dosbox_pure_savestate: "off"
        }
    },
    savestates_disabled: true,
    rewind_disabled: true,
    ffd_disabled: true,
    force_scale: true,
    video_smooth: false,
    dependencies: [
    ],
    touch_controllers: [
    ],
    mouse_controllers: [
    ],
    keyboard_controller_mapping: {
        input_player1_up: 'nul',
        input_player1_left: 'nul',
        input_player1_down: 'nul',
        input_player1_right: 'nul',
        input_player1_x: 'nul',
        input_player1_y: 'nul',
        input_player1_c: 'nul',
        input_player1_a: 'nul',
        input_player1_b: 'nul',
        input_player1_l: 'nul',
        input_player1_r: 'nul',
        input_player1_l2: 'nul',
        input_player1_r2: 'nul',
        input_player1_l3: 'nul',
        input_player1_r3: 'nul',
        input_player1_select: 'nul',
        input_player1_start: 'nul',
        input_game_focus_toggle: 'nul',
        input_auto_game_focus: '1',
        input_menu_toggle: 'nul',
        input_menu_ok: 'nul',
        input_menu_ok_btn: 'nul',
        input_menu_ok_axis: 'nul',
        input_menu_ok_mbtn: 'nul',
        input_menu_cancel: 'nul',
        input_menu_cancel_btn: 'nul',
        input_menu_cancel_axis: 'nul',
        input_menu_cancel_mbtn: 'nul',
        input_menu_back: 'nul',
        input_menu_start: 'nul',
        input_menu_start_btn: 'nul',
        input_menu_start_axis: 'nul',
        input_menu_start_mbtn: 'nul',
        input_menu_select: 'nul',
        input_menu_select_btn: 'nul',
        input_menu_select_axis: 'nul',
        input_menu_select_mbtn: 'nul',
        input_menu_up: 'nul',
        input_menu_up_btn: 'nul',
        input_menu_up_axis: 'nul',
        input_menu_down: 'nul',
        input_menu_down_btn: 'nul',
        input_menu_down_axis: 'nul',
        input_menu_left: 'nul',
        input_menu_left_btn: 'nul',
        input_menu_left_axis: 'nul',
        input_menu_right: 'nul',
        input_menu_right_btn: 'nul',
        input_menu_right_axis: 'nul',
        input_menu_page_up: 'nul',
        input_menu_page_up_btn: 'nul',
        input_menu_page_up_axis: 'nul',
        input_menu_page_down: 'nul',
        input_menu_page_down_btn: 'nul',
        input_menu_page_down_axis: 'nul',
        input_menu_home: 'nul',
        input_menu_home_btn: 'nul',
        input_menu_home_axis: 'nul',
        input_menu_end: 'nul',
        input_menu_end_btn: 'nul',
        input_menu_end_axis: 'nul',
        input_player1_gun_start: 'nul',
        input_player1_gun_start_btn: 'nul',
        input_player1_gun_start_axis: 'nul',
        input_player1_gun_start_mbtn: 'nul',
        input_player1_gun_select: 'nul',
        input_player1_gun_select_btn: 'nul',
        input_player1_gun_select_axis: 'nul',
        input_player1_gun_select_mbtn: 'nul',
    },
    touch_controller_mapping: {
        input_player1_up: 'nul',
        input_player1_left: 'nul',
        input_player1_down: 'nul',
        input_player1_right: 'nul',
        input_player1_x: 'nul',
        input_player1_y: 'nul',
        input_player1_c: 'nul',
        input_player1_a: 'nul',
        input_player1_b: 'nul',
        input_player1_l: 'nul',
        input_player1_r: 'nul',
        input_player1_l2: 'nul',
        input_player1_r2: 'nul',
        input_player1_l3: 'nul',
        input_player1_r3: 'nul',
        input_player1_select: 'nul',
        input_player1_start: 'nul',
        input_game_focus_toggle: 'nul',
        input_auto_game_focus: '1',
        input_menu_toggle: 'nul',
        input_menu_ok: 'nul',
        input_menu_ok_btn: 'nul',
        input_menu_ok_axis: 'nul',
        input_menu_ok_mbtn: 'nul',
        input_menu_cancel: 'nul',
        input_menu_cancel_btn: 'nul',
        input_menu_cancel_axis: 'nul',
        input_menu_cancel_mbtn: 'nul',
        input_menu_back: 'nul',
        input_menu_start: 'nul',
        input_menu_start_btn: 'nul',
        input_menu_start_axis: 'nul',
        input_menu_start_mbtn: 'nul',
        input_menu_select: 'nul',
        input_menu_select_btn: 'nul',
        input_menu_select_axis: 'nul',
        input_menu_select_mbtn: 'nul',
        input_menu_up: 'nul',
        input_menu_up_btn: 'nul',
        input_menu_up_axis: 'nul',
        input_menu_down: 'nul',
        input_menu_down_btn: 'nul',
        input_menu_down_axis: 'nul',
        input_menu_left: 'nul',
        input_menu_left_btn: 'nul',
        input_menu_left_axis: 'nul',
        input_menu_right: 'nul',
        input_menu_right_btn: 'nul',
        input_menu_right_axis: 'nul',
        input_menu_page_up: 'nul',
        input_menu_page_up_btn: 'nul',
        input_menu_page_up_axis: 'nul',
        input_menu_page_down: 'nul',
        input_menu_page_down_btn: 'nul',
        input_menu_page_down_axis: 'nul',
        input_menu_home: 'nul',
        input_menu_home_btn: 'nul',
        input_menu_home_axis: 'nul',
        input_menu_end: 'nul',
        input_menu_end_btn: 'nul',
        input_menu_end_axis: 'nul',
        input_player1_gun_start: 'nul',
        input_player1_gun_start_btn: 'nul',
        input_player1_gun_start_axis: 'nul',
        input_player1_gun_start_mbtn: 'nul',
        input_player1_gun_select: 'nul',
        input_player1_gun_select_btn: 'nul',
        input_player1_gun_select_axis: 'nul',
        input_player1_gun_select_mbtn: 'nul',
    },
    default_touch_controller: JOYSTICK_TOUCH_MODE.HIDEAWAY,
    disable_touch_input: true,
    fire_buttons: 1,
    keyboard: {
        shiftKey: 2,
        mode_labels: {
            retropad: 'Focus mode disabled',
            focusmode: 'Focus mode enabled'
        },
        overrides: {
        }
    },
    message: ["PC emulation is work-in-progress. You can use a keyboard and mouse or a gamepad with automatic keyboard-to-gamepad mappings, but touch controls are not yet available!"]
};

export default DOS;
