import PlatformBase from '../PlatformBase.js';
import { JOYSTICK_TOUCH_MODE } from '../../Constants.js';

const SNK = {
    ...PlatformBase,
    platform_id: 'snk',
    core: 'fbalpha2012_neogeo',
    platform_name: 'Neo Geo AES / MVS',
    short_name: 'SNK',
    theme: {
        '--color0': '#656565',
        '--color1': '#c3c3c3',
        '--color3': '#71f3f2',
        '--color2': '#000000',
        '--font': 'SNK',
        '--cursorwidth': '1em',
        '--transform': 'none'
    },
    shader: ['assets/shaders/crt/crt-geom.glslp', 'assets/shaders/crt/shaders/crt-geom.glsl'],
    guessConfig: (fileName) => {
        return {
        };
    },
    keyboard_controller_info: {
        "Cursor Keys": "Joystick movement",
        "Z": "Fire A",
        "X": "Fire B",
        "A": "Fire C",
        "S": "Fire D",
        "Right Shift": "Insert Coin",
        "Enter": "Start",
    },
    touch_controllers: [
        JOYSTICK_TOUCH_MODE.QUICKSHOT_DYNAMIC
    ],
    default_touch_controller: JOYSTICK_TOUCH_MODE.QUICKSHOT_DYNAMIC,
    fire_buttons: 4,
    name_overrides: {
        "2020bb": "2020 Super Baseball (set 1)",
        "3countb": "3 Count Bout / Fire Suplex (NGM-043 ~ NGH-043)",
        "sonicwi2": "Aero Fighters 2 / Sonic Wings 2",
        "sonicwi3": "Aero Fighters 3 / Sonic Wings 3",
        "aodk": "Aggressors of Dark Kombat / Tsuukai GANGAN Koushinkyoku",
        "alpham2": "Alpha Mission II / ASO II - Last Guardian",
        "androdun": "Andro Dunos",
        "aof": "Art of Fighting / Ryuuko no Ken",
        "aof2": "Art of Fighting 2 / Ryuuko no Ken 2",
        "aof3": "Art of Fighting 3 - The Path of the Warrior / Art of Fighting - Ryuuko no Ken Gaiden",
        "bakatono": "Bakatonosama Mahjong Manyuki",
        "bstars2": "Baseball Stars 2",
        "bstars": "Baseball Stars Professional",
        "blazstar": "Blazing Star",
        "bjourney": "Blue's Journey / Raguy",
        "breakers": "Breakers",
        "burningf": "Burning Fight (set 1)",
        "marukodq": "Chibi Marukochan Deluxe Quiz",
        "crsword": "Crossed Swords",
        "cyberlip": "Cyber-Lip",
        "doubledr": "Double Dragon (Neo-Geo)",
        "eightman": "Eight Man",
        "kabukikl": "Far East of Eden - Kabuki Klash / Tengai Makyou - Shin Den",
        "fatfury1": "Fatal Fury - King of Fighters / Garou Densetsu - Shukumei no Tatakai",
        "fatfury2": "Fatal Fury 2 / Garou Densetsu 2 - Arata-naru Tatakai",
        "fatfury3": "Fatal Fury 3 - Road to the Final Victory / Garou Densetsu 3 - Haruka-naru Tatakai",
        "fatfursp": "Fatal Fury Special / Garou Densetsu Special (set 1)",
        "fbfrenzy": "Football Frenzy",
        "galaxyfg": "Galaxy Fight - Universal Warriors",
        "garou": "Garou - Mark of the Wolves (set 1)",
        "gpilots": "Ghost Pilots",
        "karnovr": "Karnov's Revenge / Fighter's History Dynamite",
        "kotm": "King of the Monsters (set 1)",
        "kotm2": "King of the Monsters 2 - The Next Thing",
        "kizuna": "Kizuna Encounter - Super Tag Battle / Fu'un Super Tag Battle",
        "lastblad": "Last Blade / Bakumatsu Roman - Gekka no Kenshi, The (set 1)",
        "lastbld2": "Last Blade 2 / Bakumatsu Roman - Dai Ni Maku Gekka no Kenshi, The",
        "lresort": "Last Resort",
        "lbowling": "League Bowling",
        "legendos": "Legend of Success Joe / Ashitano Joe Densetsu",
        "magdrop2": "Magical Drop II",
        "magdrop3": "Magical Drop III",
        "maglord": "Magician Lord (set 1)",
        "mahretsu": "Mahjong Kyoretsuden",
        "mslug": "Metal Slug - Super Vehicle-001",
        "mslug2": "Metal Slug 2 - Super Vehicle-001-II",
        "mslug3": "Metal Slug 3",
        "mslug4": "Metal Slug 4",
        "mslug5": "Metal Slug 5",
        "mslugx": "Metal Slug X - Super Vehicle-001",
        "minasan": "Minnasanno Okagesamadesu",
        "mutnat": "Mutation Nation",
        "nam1975": "NAM-1975",
        "turfmast": "Neo Turf Masters / Big Tournament Golf",
        "neocup98": "Neo-Geo Cup '98 - The Road to the Victory",
        "ncombat": "Ninja Combat",
        "ncommand": "Ninja Commando",
        "ninjamas": "Ninja Master's - Haoh-ninpo-cho",
        "overtop": "Over Top",
        "pgm": "PGM (Polygame Master) System BIOS",
        "matrim": "Power Instinct Matrimelee",
        "pulstar": "Pulstar",
        "joyjoy": "Puzzled / Joy Joy Kid",
        "quizdais": "Quiz Daisousa Sen - The Last Count Down",
        "quizkof": "Quiz King of Fighters",
        "quizdai2": "Quiz Meitantei Neo and Geo - Quiz Daisousa Sen part 2",
        "rotd": "Rage of the Dragons",
        "ragnagrd": "Ragnagard / Shin-Oh-Ken",
        "rbff1": "Real Bout Fatal Fury / Real Bout Garou Densetsu",
        "rbff2": "Real Bout Fatal Fury 2 - The Newcomers / Real Bout Garou Densetsu 2 - The Newcomers (set 1)",
        "rbffspec": "Real Bout Fatal Fury Special / Real Bout Garou Densetsu Special",
        "ridhero": "Riding Hero (set 1)",
        "roboarmy": "Robo Army",
        "samsho": "Samurai Shodown / Samurai Spirits",
        "samsho2": "Samurai Shodown II / Shin Samurai Spirits - Haohmaru jigokuhen",
        "samsho3": "Samurai Shodown III / Samurai Spirits - Zankurou Musouken",
        "samsho4": "Samurai Shodown IV - Amakusa's Revenge / Samurai Spirits - Amakusa Kourin",
        "samsho5": "Samurai Shodown V",
        "samsh5sp": "Samurai Shodown V Special",
        "savagere": "Savage Reign / Fu'un Mokushiroku - kakutou sousei",
        "sengoku": "Sengoku / Sengoku Denshou (set 1)",
        "sengoku2": "Sengoku 2 / Sengoku Denshou 2",
        "sengoku3": "Sengoku 3",
        "shocktr2": "Shock Troopers - 2nd Squad",
        "socbrawl": "Soccer Brawl",
        "spinmast": "Spin Master / Miracle Adventure",
        "stakwin": "Stakes Winner / Stakes Winner - GI kinzen seihae no michi",
        "stakwin2": "Stakes Winner 2",
        "strhoop": "Street Hoop / Street Slam / Dunk Dream",
        "ssideki": "Super Sidekicks / Tokuten Ou",
        "ssideki2": "Super Sidekicks 2 - The World Championship / Tokuten Ou 2 - Real Fight Football",
        "ssideki3": "Super Sidekicks 3 - The Next Glory / Tokuten Ou 3 - eikoue no michi",
        "svc": "SvC Chaos - SNK vs Capcom (MVS)",
        "mosyougi": "Syougi No Tatsujin - Master of Syougi",
        "kof94": "The King of Fighters '94",
        "kof95": "The King of Fighters '95 (set 1)",
        "kof96": "The King of Fighters '96 (set 1)",
        "kof97": "The King of Fighters '97 (set 1)",
        "kof98": "The King of Fighters '98 - The Slugfest - King of Fighters '98 / Dream Match Never Ends",
        "kof99": "The King of Fighters '99 - Millennium Battle (set 1)",
        "kof2000": "The King of Fighters 2000",
        "kof2001": "The King of Fighters 2001",
        "kof2002": "The King of Fighters 2002",
        "kof2003": "The King of Fighters 2003 (World / US, MVS)",
        "superspy": "The Super Spy",
        "trally": "Thrash Rally",
        "tophuntr": "Top Hunter - Roddy and Cathy",
        "tpgolf": "Top Player's Golf",
        "twinspri": "Twinkle Star Sprites",
        "ssideki4": "Ultimate 11 - The SNK Football Championship / Tokuten Ou - Honoo no Libero, The",
        "viewpoin": "Viewpoint",
        "gowcaizr": "Voltage Fighter - Gowcaizer / Choujin Gakuen Gowcaizer",
        "wakuwak7": "Waku Waku 7",
        "wjammers": "Windjammers / Flying Power Disc",
        "wh1": "World Heroes (set 1)",
        "wh2": "World Heroes 2",
        "wh2j": "World Heroes 2 Jet",
        "whp": "World Heroes Perfect"
    },
    button_overrides: {
        "3countb": 4, //a,b,c,a+b
        "2020bb": 4,
        "alpham2": 3,
        "androdun": 2,
        "aodk": 4, 
        "aof": 4, 
        "aof2": 4,
        "aof3": 4,
        "bakatono": 4, //19
        "bjourney": 3,
        "blazstar": 2,
        "breakers": 4,
        "bstars": 4,
        "bstars2": 4,
        "burningf": 3, //a,b,c,a+b
        "crsword": 2,
        "cyberlip": 3,
        "doubledr": 4,
        "eightman": 3, //a,a+b,c
        "fatfursp": 4,
        "fatfury1": 4,
        "fatfury2": 4,
        "fatfury3": 4,
        "fbfrenzy": 4,
        "galaxyfg": 4,
        "garou": 4,
        "gowcaizr": 4,
        "gpilots": 2,
        "joyjoy": 2,
        "kabukikl": 4, //+
        "karnovr": 4,
        "kizuna": 4,
        "kof94": 4,
        "kof95": 4,
        "kof96": 4,
        "kof97": 4,
        "kof98": 4,
        "kof99": 4,
        "kof2000": 4,
        "kof2001": 4,
        "kof2002": 4,
        "kof2003": 4,
        "kotm": 3,
        "kotm2": 3,
        "lastblad": 4,
        "lastbld2": 4,
        "lbowling": 1,
        "legendos": 2,
        "lresort": 2,
        "magdrop2": 2,
        "magdrop3": 3,
        "maglord": 2,
        "mahretsu": 2,
        "marukodq": 4, //?
        "matrim": 4,
        "minasan": 0,
        "mosyougi": 0,
        "mslug": 3, //+
        "mslug2": 3, //+
        "mslug3": 3, //+
        "mslug4": 4,
        "mslug5": 4,
        "mslugx": 3, //+
        "mutnat": 2,
        "nam1975": 3,
        "ncombat": 3,
        "ncommand": 3,
        "neocup98": 3,
        "ninjamas": 4,
        "overtop": 2, //?
        "pulstar": 2,
        "quizdai2": 4, //?
        "quizdais": 4, //?
        "quizkof": 4, //?
        "ragnagrd": 4,
        "rbff1": 4,
        "rbff1a": 4,
        "rbff2": 4,
        "rbffspec": 4,
        "ridhero": 3,
        "roboarmy": 3,
        "rotd": 4,
        "samsh5sp": 4,
        "samsho": 4,
        "samsho2": 4,
        "samsho3": 4,
        "samsho4": 4,
        "samsho5": 4,
        "savagere": 4,
        "sengoku": 3,
        "sengoku2": 4,
        "sengoku3": 4,
        "shocktr2": 4,
        "socbrawl": 2,
        "sonicwi2": 2,
        "sonicwi3": 2,
        "spinmast": 3,
        "ssideki": 2,
        "ssideki2": 3,
        "ssideki3": 3,
        "ssideki4": 3,
        "stakwin": 2,
        "stakwin2": 3,
        "strhoop": 2,
        "superspy": 3,
        "svc": 4, //+
        "tophuntr": 3,
        "tpgolf": 4,
        "trally": 2,
        "turfmast": 3,
        "twinspri": 2,
        "viewpoin": 2,
        "wakuwak7": 4,
        "wh1": 3,
        "wh2": 3,
        "wh2j": 3,
        "whp": 4, //+
        "wjammers": 2
    },
    additional_buttons: {
        1: {
            "label": "COIN",
            "keyCode": 'select'
        },
        2: {
            "label": "START",
            "keyCode": 'start'
        }
    },
};

export default SNK;